Add files via upload
Yash080902/Team-AMBU_Web_Work pull request #2
Opened 2023-05-20 10:21 UTC by VishnuKumarVerma

Profile Page AMBU Final is ready to preview...you can check it via my directory

2023-05-20 10:25 UTC, Yash080902 commented
Okay vishnu
I will do that today
Tell this  also to Vishesh.


Well-done guys

On Sat, 20 May 2023, 15:52 Vishnu Kumar Verma, ***@***.***>
wrote:

> Profile Page AMBU Final is ready to preview...you can check it via my
> directory
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2
> Commit Summary
>
>    - 1007167
>    <https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2/commits/100716752b0108a5732d0a55302f6e5df9d83c48>
>    Add files via upload
>
> File Changes
>
> (11 files <https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2/files>)
>
>    - *A* Profile Page AMBU/Profile-Page-AMBU/README.md
>    <https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2/files#diff-8b6cc3c3bb2243e48cd41cf05e9677e8d46e11068fa5f0509bbae35cad6920cb>
>    (4)
>    - *A* Profile Page AMBU/image/edit.png
>    <https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2/files#diff-212f731e9c004033a28d6bc60dd2ccc8a5aaf98f9344bb732d8855ff815f79f5>
>    (0)
>    - *A* Profile Page AMBU/image/help.png
>    <https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2/files#diff-ab0855a114e23c7d58c7a40224177444025d1bb14c200072b85efcce93aedc0d>
>    (0)
>    - *A* Profile Page AMBU/image/logo.png
>    <https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2/files#diff-f8fd5b2bec28764911916c30e0941e4e73989d06c9585b8416f7d263a738f99f>
>    (0)
>    - *A* Profile Page AMBU/image/notification.png
>    <https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2/files#diff-78f75879d1976d14d8a6bb06af852b2437e0628e85ef95df1b389c39e40e0fc1>
>    (0)
>    - *A* Profile Page AMBU/image/profile.png
>    <https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2/files#diff-ee14187967dadf1b2dc4c264f9380f7bec33897999a9f57d5717874bcbe9d158>
>    (0)
>    - *A* Profile Page AMBU/image/translate.png
>    <https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2/files#diff-cca168f94c66ff4baaee4035cbece623109d97a990d9b439798e50b4bf0a8bc7>
>    (0)
>    - *A* Profile Page AMBU/image/user.png
>    <https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2/files#diff-95940110a0636299b37cfd65ead25ee84dbc1880ebc1d164004ae07b5c451187>
>    (0)
>    - *A* Profile Page AMBU/index.html
>    <https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2/files#diff-d7e0b1f4f106f67754680985e6572e5a13435f8ac5d0c41be0ec99a272e58ef4>
>    (197)
>    - *A* Profile Page AMBU/script.js
>    <https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2/files#diff-8a077ba83f90b36ee08aa98787e52a98918adaf6aa18539c974678b1e6b766b9>
>    (0)
>    - *A* Profile Page AMBU/style.css
>    <https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2/files#diff-a71aa65f2e4186b807b5023d41ebdac5d906f3e821885f0b166a0013f5014df0>
>    (424)
>
> Patch Links:
>
>    - https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2.patch
>    - https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3MOY2VKIX4JKBHRVYW5Q3DXHCLM5ANCNFSM6AAAAAAYIUYA6A>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-05-20 19:58 UTC, onlyVishesh commented
sir i also done mostly all the things please check my pr

2023-05-20 23:41 UTC, Yash080902 commented
Okay vishesh I will do that
Sorry for the inconvenience because I am at my home.
Today we will confirm

On Sun, 21 May 2023, 01:28 Vishesh, ***@***.***> wrote:

> sir i also done mostly all the things please check my pr
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Yash080902/Team-AMBU_Web_Work/pull/2#issuecomment-1555983021>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3MOY2XWNW2BL7FVPD5Z6MTXHEO5TANCNFSM6AAAAAAYIUYA6A>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-05-22 16:20 UTC, Yash080902 requested changes
Do these kind of changes ASAP

2023-05-22 16:20 UTC, Yash080902 commented on Profile Page AMBU/image/edit.png
Vishnu please make it more interactive okay 
even it is looking good
nice

2023-05-22 16:20 UTC, Yash080902 commented on Profile Page AMBU/image/notification.png
try to change the color of the bell icon

2023-05-22 16:20 UTC, Yash080902 commented on Profile Page AMBU/index.html
> +                  <label for="User-email">EMAIl ID</label>
Make the text of EMAIL proper either in block or small

2023-05-29 12:10 UTC, closed without merging